package rtcf.commonlib.enumeration;

/**
 * Enumerato per la definizione dei messaggi di errore per i command result
 * Utilizzato da
 * @author CSS
 */
public enum ErrorCode {
 //COMMON
 EXECUTED(0, "EXECUTED"),
 TIMEOUT_EXPIRED(1, "TIMEOUT EXPIRED"),
 COMMAND_NOT_VALID(2, "COMMAND NOT VALID"),
 ITEM_ALREADY_EXISTS(3, "ITEM ALREADY EXISTS"),
 COMMAND_NOT_EXECUTED(4, "COMMAND_NOT_EXECUTED"),
 INVALID_VALUE(5, "INVALID VALUE"),
 SYSTEM_NOT_OPERATIVE(6,"SYSTEM_NOT_OPERATIVE"),
 JMS_EXCEPTION(7,"JMS BROKER NOT AVAILABLE"),

 //NAV 1000
 NO_SOLUTION(1000, "NO SOLUTION"),
 WRONG_ENVIRONMENT(1001, "WRONG ENVIRONMENT"),
 WRONG_KINEMATICS(1002, "WRONG KINEMATICS"),
 WP_OP_NOT_PERMITTED(1003, "WP OPERATION NOT PERMITTED"),
 NAV_PLAN_NOT_VALID(1004,"NAV PLAN NOT VALID"),
 WP_WP_NOT_VALID(1005,"WAYPOINT NOT VALID"),
 MAX_SPEED_ERR(1006,"SPEED ERROR: SPEED GREATER THAN MAXIMUM VALUE"),
 INVALID_MASTER_TRACK(1007,"INVALID MASTER TRACK"),
 NAV_INTERNAL_ERROR(1008,"NAV INTERNAL ERROR"),
 NAV_PLAN_NOT_FOUND(1009,"NAV PLAN NOT FOUND"),
 SESSION_EXISTS(1010,"ANOTHER SESSION ALREADY EXISTS"),
 ACTIVE_ALREADY_PLAN_EXIST(1011,"ACTIVE PLAN ALREADY EXISTS"),
 ACTIVE_PLAN_LOCK(1012,"ACTIVE PLAN LOCK"),
 INVALID_SURFACE_TRACK(1013, "INVALID SURFACE TRACK"),
 NAV_AREA_PER_TRACK_LIMIT(1014, "NAV AREA PER TRACK LIMIT"),
 NAV_AREA_NOT_VALID(1015,"NAV AREA NOT VALID"),
 NAME_ALREADY_EXIST(1016,"NAME ALREADY EXIST"),
 WP_LEG_DISTANCE_NULL(1017,"WP LEG DISTANCE CANNOT BE NULL"),
 SPEED_ERR(1018,"INVALID SPEED ERR"),
 TIME_ERR(1019,"INVALID TIME ERR"),
 INVALID_NAME_ERR(1020,"INVALID NAME"),
 INVALID_IDX(1021,"INVALID INDEX"),
 EMPTY_WP_LIST(1022,"WP LIST IS EMPTY"),
 WP_STATION_RANGE_NULL(1023,"WP STATION RANGE IS NULL"),
 WP_INVALID_PATROL_TIME(1024,"WP INVALID PATROL TIME"),
 INTERSECTION_ERROR(1025, "INTERSECTION ERROR"),
 INVALID_GUIDE_TRACK(1025,"INVALID GUIDE TRACK"),
 INVALID_STATIONING_RANGE(1026,"INVALID STATIONING RANGE"),
 INVALID_STATION_TOLERANCE(1027,"INVALID STATION TOLERANCE"),
 STATIONING_NOT_ACTIVE(1028,"STATIONING IS NOT ACTIVE"),
 INVALID_STATION_RANGE(1029,"INVALID STATION RANGE"),
 INVALID_TARGET_TRACK(1030,"INVALID TARGET TRACK"),
 STATIONING_ACTIVE(1031,"STATIONING IS ACTIVE"),
 NO_ACTIVE_PLAN(1032,"NO ACTIVE PLAN"),
 PIM_CALC_ERROR(1033,"PIM CALC ERROR"),
 NAV_MAX_LEGS_NUMBER_ERROR(1034,"NAV MAX LEGS NUMBER ERROR"),
 MONITORING_ACTIVE(1035,"MONITORING IS ACTIVE"),
 GEOGRAPHIC_ERROR(1036,"GEOGRAPHIC ERROR"),
 NAV_COMPONENT_NOT_AVAILABLE(1099,"NAV COMPONENT NOT AVAILABLE"),
 //WAP 2000
 PLATFORM_INVALID(2000, "INVALID PLATFORM OR PLATFORM SPECIFIC"),
 CSSN_INVALID(2001, "INVALID CSSN"),
 WRONG_TRACK_TYPE(2002,"CAN NOT REMOVE RT TRACK"),
 TRACK_DOES_NOT_EXIST(2003,"TRACK DOES NOT EXIST"),
 TRACK_NOT_CORRELABLE(2004,"TRACK NOT CORRELABLE"),
 TRACK_RT_NOT_CORRELABLE(2005,"TRACK RT NOT CORRELABLE"),
 TRACK_OTH_NOT_CORRELABLE(2006,"TRACK OTH NOT CORRELABLE"),
 ENVIRONMENT_COMPARE_ERROR(2007, "ENVIRONMENT COMPARE ERROR"),
 IDENTITY_NOT_COMPATIBLE(2008, "IDENTITY NOT COMPATIBLE"),
 NO_INTERSECTION(2009, "NO INTERSECTION"),
 NO_PARAMETER(2010, "NO PARAMETER"),
 WRONG_TRACK(2011,"WRONG TRACK"),
 NOT_EXISTING_TRACK(2012,"NOT EXISTING TRACK"),
 WAP_COMPONENT_NOT_AVAILABLE(2099, "WAP COMPONENT NOT AVAILABLE"),
 //PLN 3000
 PLN_INTERNAL_ERROR(3001,"PLN INTERNAL ERROR"),
 MAX_SHIP_NUMBER(3002,"MAX SHIP NUMBER"),
 MISSION_PLAN_NOT_FOUND(3003,"MISSION PLAN NOT FOUND"),
 MISSION_PLAN_NOT_VALID(3004,"MISSION PLAN NOT VALID"),
 ITEM_NOT_SAVED(3005,"ITEM NOT SAVED"),
 ITEM_NOT_UPDATED(3006,"ITEM NOT UPDATED"),
 ITEM_NOT_FOUND(3007,"ITEM NOT FOUND"),
 NO_NAV_PLANS_AVAILABLE(3008,"NO NAV PLANS AVAILABLE"),
 MISSION_PLAN_NAME_EXIST(3009,"MISSION PLAN NAME EXIST"),
 MISSION_PLAN_NAME_NOT_VALID(3010,"MISSION PLAN NAME NOT VALID"),
 STATION_ALREADY_ALLOCATED(3011,"STATION ALREADY ALLOCATED"),
 SHIP_ALREADY_ALLOCATED(3012,"SHIP ALREADY ALLOCATED"),
 SHIP_NOT_ASSIGNED(3013,"SHIP_NOT_ASSIGNED"),
 SHIP_LIST_EMPTY(3014,"STATION LIST EMPTY"),
 FORCE_DISPOSITION_NOT_VALID(3015,"FORCE_DISPOSITION_NOT_VALID"),
 SURVEILLANCE_DUTY_INVALID(3016,"SURVEILLANCE DUTY INVALID"),
 WARFARE_DUTY_INVALID(3017,"WARFARE DUTY INVALID"),
 SQL_EXCEPTION(3018,"SQL EXCEPTION"),
 NEW_POSITION_EVALUATION(3019,"NEW POSITION EVELUATION ERROR"),
 DUTY_INVALID(3020,"DUTY INVALID"),
 SAR_MISSION_NOT_VALID(3021,"SAR MISSION NOT VALID OR NULL"),
 SAR_MISSION_ALREADY_ACTIVE(3022,"SAR MISSION ALREADY ACTIVE"),
 SAR_MISSION_INVALID_TIME(3023,"SAR MISSION INVALID TIME"),
 SAR_MISSION_INVALID_METEO_DATA(3024,"SAR MISSION INVALID METEO DATA"),
 //DBM 4000
 DB_NOT_AVAILABLE(4099,"DB NOT AVAILABLE"),

 //HCI 5000
 MISSION_PLAN_MISSING_DATA(5001,"MISSING DATA"),

 //BAS 6000
 INVALID_ACCOUNT(6000,"INVALID ACCOUNT"),
 CONCURRENT_ROLES_EXCEEDED(6001,"CONCURRENT ROLES EXCEEDED"),
 INVALID_SESSION(6002,"INVALID SESSION"),
 EMPTY_LIST(6003,"EMPTY LIST"),
 ACCOUNT_ALREADY_LOGGED(6004,"ACCOUNT_ALREADY_LOGGED"),

 //COM 7000
 MTF_MSG_PARSING_ERROR(7000, "MTF_MSG_PARSING_ERROR"),
 MTF_MSG_RMPNODE_SENDING_EXCEPTION(7001, "MTF_MSG_RMPNODE_SENDING_EXCEPTION"),
 MTF_MSG_RMPNODE_SENDING_ERROR_NO_NODES(7002, "MTF_MSG_RMPNODE_SENDING_ERROR_NO_NODES"),
 MTF_MSG_RMPNODELIST_NOT_VALID(7003, "MTF_MSG_RMPNODELIST_NOT_VALID"),
 //COM 9000
 CMG_CONNECTION_REFUSED(9001, "CMG SESSION NOT INSTANCED"),
 CMG_METOC_NOT_AVAILABLE(9002, "Metoc Service is not availble"),
 CMG_AIS_SERVICE_NOT_AVAILABLE(9003, "AIS Service is not available"),

//GIS 8000
 GIS_COMPONENT_NOT_AVAILABLE(8000,"GIS COMPONENT NOT AVAILABLE");
 
 private ErrorCode(int value, String abbreviation) {
   this.abbreviation = abbreviation;
   this.int_value = value;
 }

 public String getAbbreviation() { return abbreviation; }
 public int getIntValue() { return int_value; }

 private String abbreviation;
 private int int_value;
}
