package rtcf.commonlib.enumeration;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * defines the enumeration of the Nationality
 *
 * @author CSS
 */

public enum Nationality implements java.io.Serializable {

	NO_STATEMENT(0, "NO_STATEMENT", "NS"),
	USSR_SOVIET_UNION(30, "USSR_SOVIET_UNION", "UR"),
	NATO(31, "NATO", "NA"),
	BELGIUM(32, "BELGIUM", "BE"),
	CYPRUS(33, "CYPRUS", "CY"),
	DENMARK(34, "DENMARK", "DE"),
	FRANCE(35, "FRANCE", "FR"),
	GERMANY(36, "GERMANY", "GE"),
	FINLAND(37, "FINLAND", "FI"),
	GREECE(38, "GREECE", "GR"),
	ICELAND(39, "ICELAND", "IC"),
	IRELAND(40, "IRELAND", "IR"),
	ITALY(41, "ITALY", "IT"),
	NETHERLANDS(42, "NETHERLANDS", "NL"),
	NORWAY(43, "NORWAY", "NO"),
	PORTUGAL(44, "PORTUGAL", "PO"),
	SPAIN(45, "SPAIN", "ES"),
	SWEDEN(46, "SWEDEN", "SW"),
	SWITZERLAND(47, "SWITZERLAND", "CH"),
	TURKEY(48, "TURKEY", "TU"),
	UNITED_KINGDOM(49, "UNITED_KINGDOM", "UK"),
	ALBANIA(50, "ALBANIA", "AL"),
	AUSTRIA(51, "AUSTRIA", "OS"),
	BULGARIA(52, "BULGARIA", "BU"),
	CZECHOSLOVAKIA(53, "CZECHOSLOVAKIA", "CZ"),
	HUNGARY(55, "HUNGARY", "HU"),
	POLAND(56, "POLAND", "PO"),
	RUMANIA(57, "RUMANIA", "RO"),
	YUGOSLAVIA(58, "YUGOSLAVIA", "YU"),
	CANADA(59, "CANADA", "CA"),
	UNITED_STATES_OF_AMERICA(60, "UNITED_STATES_OF_AMERICA", "US"),
	EGYPT(61, "EGYPT", "EG"),
	IRAN(62, "IRAN", "IR"),
	IRAQ(63, "IRAQ", "IQ"),
	ISRAEL(64, "ISRAEL", "IS"),
	JORDAN(65, "JORDAN", "JR"),
	LEBANON(66, "LEBANON", "LE"),
	SAUDI_ARABIA(67, "SAUDI_ARABIA", "SA"),
	SYRIA(68, "SYRIA", "SY"),
	ALGERIA(69, "ALGERIA", "AL"),
	ETHIOPIA(70, "ETHIOPIA", "ET"),
	LIBERIA(71, "LIBERIA", "LI"),
	LIBYA(72, "LIBYA", "LB"),
	SOUTH_AFRICA(73, "SOUTH_AFRICA", "SF"),
	INDIA(74, "INDIA", "IN"),
	PAKISTAN(75, "PAKISTAN", "PK"),
	CAMBODIA(76, "CAMBODIA", "CM"),
	LAOS(77, "LAOS", "LA"),
	THAILAND(78, "THAILAND", "TH"),
	VIETNAM(79, "VIETNAM", "VI"),
	CHINA_PEOPLE_REPUBLIC(80, "CHINA_PEOPLE_REPUBLIC", "CP"),
	CHINA_REPUBLIC(81, "CHINA_REPUBLIC", "CR"),
	KOREA_NORTH(82, "KOREA_NORTH", "KN"),
	KOREA_REPUBLIC(83, "KOREA_REPUBLIC", "KR"),
	JAPAN(84, "JAPAN", "JP"),
	PHILIPPINES(85, "PHILIPPINES", "PH"),
	AUSTRALIA(86, "AUSTRALIA", "AU"),
	NEW_ZEALAND(87, "NEW_ZEALAND", "NZ"),
	ARGENTINA(88, "ARGENTINA", "AR"),
	BRAZIL(89, "BRAZIL", "BR"),
	CHILE(90, "CHILE", "CI"),
	COLUMBIA(91, "COLUMBIA", "CO"),
	MEXICO(92, "MEXICO", "ME"),
	PANAMA(93, "PANAMA", "PA"),
	PERU(94, "PERU", "PE"),
	VENEZUELA(95, "VENEZUELA", "VE"),
	CUBA(96, "CUBA", "CU"),
	DOMINICAN_REPUBLIC(97, "DOMINICAN_REPUBLIC", "DR"),
	UNITED_NATIONS_FORCE(98, "UNITED_NATIONS_FORCE", "UN"),
	KUWAIT(99, "KUWAIT", "KU"),
	YEMEN_ARAB_REPUBLIC(100, "YEMEN_ARAB_REPUBLIC", "YA"),
	GUINEA(101, "GUINEA", "GU"),
	MALAGASY_MADAGASCAR(102, "MALAGASY_MADAGASCAR", "MD"),
	MOROCCO(103, "MOROCCO", "MR"),
	NIGERIA(104, "NIGERIA", "NI"),
	SENEGAL(105, "SENEGAL", "SE"),
	ZIMBABWE(106, "ZIMBABWE", "ZI"),
	SPANISH_NORTH_AFRICA(107, "SPANISH_NORTH_AFRICA", "SN"),
	SUDAN(108, "SUDAN", "SU"),
	TANZANIA(109, "TANZANIA", "TA"),
	TUNISIA(110, "TUNISIA", "TU"),
	UGANDA(111, "UGANDA", "UG"),
	BURMA(112, "BURMA", "BU"),
	INDONESIA(113, "INDONESIA", "IN"),
	MALAYSIA(114, "MALAYSIA", "MA"),
	SINGAPORE(115, "SINGAPORE", "SI"),
	BOLIVIA(116, "BOLIVIA", "BO"),
	ECUADOR(117, "ECUADOR", "EC"),
	GUATEMALA(118, "GUATEMALA", "GU"),
	NICARAGUA(119, "NICARAGUA", "NI"),
	PARAGUAY(120, "PARAGUAY", "PA"),
	URUGUAY(121, "URUGUAY", "UR"),
	JAMAICA(122, "JAMAICA", "JA"),
	INTERNATIONAL_RED_CROSS(123, "INTERNATIONAL_RED_CROSS", "IR"),
	LUXEMBOURG(124, "LUXEMBOURG", "LU"),
	YEMEN_PEOPLES_DEMOCRATIREPUBLIC(125, "YEMEN_PEOPLES_DEMOCRATIREPUBLIC", "YP"),
	UAE(125, "UNITED_ARABIAN_EMIRATES", "UA"),
	RESET_TO_NO_STATEMENT(126, "RESET_TO_NO_STATEMENT", "RN");

	private Nationality(int value, String abbreviation, String biLetter) {
		this.intValue = value;
		this.abbreviation = abbreviation;
		this.biLetter = biLetter;
	}

	public String getAbbreviation() { return abbreviation; }
	public int getIntValue() { return intValue;}

	public String getBiLetter() {
		return biLetter;
	}

	int intValue = 0;
	private String abbreviation;
	private String biLetter;



}
